version: "3.8"
services: 
  frontend:
    build: ./client
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - mern-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  backend: 
    build: ./
    ports:
      - 5000:5000
    networks:
      - mern-app
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  mern-app:
    driver: bridge