name: Build and Deploy Docker Image to Droplet

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
     
    # Build the Docker image for the backend
    - name: Build backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: false
        tags: chathushkarodrigo/cdap-backend:${{ github.sha }}
      
    #Specified path to client folder  
    - name: Build and test
      run: cd client/
    

    # Build the Docker image for the frontend
    - name: Build frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: false
        tags: chathushkarodrigo/cdap-frontend:${{ github.sha }}
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: chathushkarodrigo
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Push the Docker images to Docker Hubs
    - name: Push Docker images to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          chathushkarodrigo/cdap-frontend:${{ github.sha }}
          chathushkarodrigo/cdap-backend:${{ github.sha }}
  
    # Deploy Docker images to DigitalOcean Droplet
    - name: SSH into remote server
      uses: appleboy/ssh-action@master
      with:
        host: 104.248.52.110
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ls -ltr
          docker pull chathushkarodrigo/cdap-frontend:${{ github.sha }}
          docker pull chathushkarodrigo/cdap-backend:${{ github.sha }}
          docker rmi -f chathushkarodrigo/cdap-backend$(git log -1 --pretty=format:"%h")
          docker rmi -f chathushkarodrigo/cdap-frontend$(git log -1 --pretty=format:"%h")
          docker run -d -p 5000:5000 chathushkarodrigo/cdap-backend:${{ github.sha }}
          docker run -d -p 3001:3000 chathushkarodrigo/cdap-frontend:${{ github.sha }}
          

    