name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.10
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
     
    # Build the Docker image for the backend
    - name: Build backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: false
        tags: chathushkarodrigo/cdap-backend:${{ github.sha }}
      
    #Specified path to client folder  
    - name: Build and test
      run: cd client/
    

    # Build the Docker image for the frontend
    - name: Build frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: false
        tags: chathushkarodrigo/cdap-frontend:${{ github.sha }}
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: chathushkarodrigo
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Push the Docker images to Docker Hub
    - name: Push Docker images to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          chathushkarodrigo/cdap-frontend:${{ github.sha }}
          chathushkarodrigo/cdap-backend:${{ github.sha }}
  
    # Install DigitalOcean CLI
    - name: Install DigitalOcean CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        sudo curl -sL https://repos.insights.digitalocean.com/install.sh | sudo bash
    
    # Authenticate DigitalOcean
    - name: Authenticate with DigitalOcean
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_TOKEN }}
    
    #Deploy to DigitalOcean pull & run backend
    - name: Deploy Docker image to DigitalOcean backend
      run: |
        doctl compute ssh ubuntu-s-1vcpu-512mb-10gb-nyc1-01 --ssh-command "docker pull chathushkarodrigo/cdap-frontend:${{ github.sha }} && docker run -d -p 80:80 chathushkarodrigo/cdap-frontend:${{ github.sha }}"

    #Deploy to DigitalOcean pull & run frontend
    - name: Deploy Docker image to DigitalOcean frontend
      run: |
        doctl compute ssh ubuntu-s-1vcpu-512mb-10gb-nyc1-01 --ssh-command "docker pull chathushkarodrigo/cdap-backend:${{ github.sha }} && docker run -d -p 80:80 chathushkarodrigo/cdap-backend:${{ github.sha }}"