name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
     
    # Build the Docker image for the backend
    - name: Build backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: backend
        push: false
        tags: chathushkarodrigo/backend:latest
      
    #Specified path to client folder  
    - name: Build and test
      run: cd client/
    

    # Build the Docker image for the frontend
    - name: Build frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: frontend
        push: false
        tags: chathushkarodrigo/frontend:latest
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: chathushkarodrigo
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Push the Docker images to Docker Hub
    - name: Push Docker images to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          chathushkarodrigo/frontend:latest
          chathushkarodrigo/backend:latest